### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by ibnnajjaar** [Javaabu/paperless#1]
- [ ] Add database migration files
- - [x] Appliaction types
- - [x] entity types
- - [x] document types
- - [x] services
- - [x] Applicaiton type entity type
- - [x] Application type service
- - [x] Application type documents
- - [x] Form sections
- - [x] Field groups
- - [x] Form fields
- - [x] Applications
- - [x] Form Inputs
- [x] Add migration publishing capability
- [x] Add models 
- - [x] Application type
- - [x] Entity Type // cannot be changed -- seed on start
- - [x] Document Type
- - [x] Service
- - [x] Form Section
- - [x] Field Group
- - [x] Form Field
- - [x] Application
- - [x] Form Input
- [x] Define model location in config (allows extending)
- [ ] Define field types class, allow extending and adding extra fields
- [ ] Defining default transitions, and allowing it to be extended
- [ ] Dynamic casting of application status, so we can extend it 
- [ ] Define application status class in config
- [ ] Define an abstract policy class and define default policies // add to docs to create a new policy class
- [ ] Add application status action class as an abstract class and add the methods using traits
- [ ] Add a command to add a new application type: 
- - [ ] Add an applicaiton type to config
- - [ ] Create field definition class
- - [ ] Create a service class
- - [ ] Add any relevant information
- [ ] Remove application types enum and move any required data to its individual application type class.
- [ ] create a command to initialize paperless (paperless:install)
- - [ ] Add menu items under "Paperless" menu item
- - [ ] publish migrations
- [ ] Paperless config should have a key to define entity types enum
- [ ] Command: component creation -> with builder and view and component class
- [ ] DOCUMENT IT!!!
